package br.com.article.optimisticlock.inventory.model

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey

@DynamoDbBean
class Inventory {

    @get:DynamoDbPartitionKey
    @get:DynamoDbAutoGeneratedUuid
    @get:DynamoDbAttribute("id")
    var partitionKey: String? = null

    @get:DynamoDbAttribute("quantity")
    var quantity: Int = 0

    @get:DynamoDbVersionAttribute
    @get:DynamoDbAttribute("version")
    var version: Int? = null
}